### ISSUE TITLE
Change Dashi icons behavior

### ISSUE THREAD

**Issue by gabbanaesteban** [DannyFeliz/Dashi#32]
## Change each dashi icons that represent whats going on in a pull request.

- [x] Create a Purple Dashi icon for Merge Request. #34
- [x] Create a Blue Dashi icon for information purpose. #34 
- [ ] Change dashi icons use.

 As follows:

**Green Dashi Icon:**

- PR Review

**Purple Dashi Icon:**

- PR Merged

**Yellow Dashi Icon:**

- PR Changes

**Red Dashi icon:**

- Denied PR

**Blue Dashi icon:**

- Mentioned in a PR

**Comment by DannyFeliz** [comment]
Ok, cool. 

But I think that the `Merged PR` should be purple as Github

**Comment by dawin09** [comment]
Done in PR #34

**Comment by gabbanaesteban** [comment]
@dawin09 are you sure this issue was done in PR #34? 
Dont think the behavior has chanhed.

**Comment by gabbanaesteban** [comment]
- [x] Create a Blue Dashi icon for information purpose. #34 
- [x] Create a Purple Dashi icon for Merge Request. #34
- [] Change dashi icons use.

**Comment by gabbanaesteban** [comment]
#82
